title: Sebastián Aguilar
logo: /assets/img/personal_img.png
description: >
  PhD student at Universidad de Concepción, I am part of the Planet Formation Group lead by Dr. Leonardo Krapp. My areas of expertise are theoretical and computational astrophysics. I have experience in developing theoretical models and numerical simulations for the study of astrophysical phenomena. I am also an user of the high-performance cluster KULTRUN located in the astronomy department at Universidad de Concepción.
  <br><br>
  <a href="https://github.com/saguilar2000">Visit my Github profile</a>
  Contact me at <a href="srodriguez2018@udec.cl">srodriguez2018@udec.cl</a>
#show_downloads: true
theme: jekyll-theme-minimal
